### ISSUE TITLE
Uncaught Exception call to Symphony\yaml

### ISSUE THREAD

**Issue by dg01d** [dg01d/nanopub#12]
Copying from #11 

Trying to get nanopub working on a site running PHP7, and getting errors.

`php composer.phar install` worked:
```
# php composer.phar install
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Package operations: 19 installs, 0 updates, 0 removals
  - Installing guhelski/forecast-php (1.1.1): Downloading (100%)
  - Installing psr/http-message (1.0.1): Downloading (100%)
  - Installing guzzlehttp/psr7 (1.4.2): Downloading (100%)
  - Installing guzzlehttp/promises (v1.3.1): Downloading (100%)
  - Installing guzzlehttp/guzzle (6.3.0): Downloading (100%)
  - Installing j7mbo/twitter-api-php (1.0.6): Downloading (100%)
  - Installing p3k/timezone (0.1.0): Downloading (100%)
  - Installing mf2/mf2 (v0.3.2): Downloading (100%)
  - Installing indieweb/link-rel-parser (0.1.3): Downloading (100%)
  - Installing p3k/http (0.1.5): Downloading (100%)
  - Installing zendframework/zendxml (1.0.2): Downloading (100%)
  - Installing miniflux/picofeed (v0.1.37): Downloading (100%)
  - Installing facebook/graph-sdk (5.6.1): Downloading (100%)
  - Installing ezyang/htmlpurifier (v4.9.3): Downloading (100%)
  - Installing dg/twitter-php (v3.6): Downloading (100%)
  - Installing cebe/markdown (1.1.2): Downloading (100%)
  - Installing p3k/xray (v1.4.2): Downloading (100%)
  - Installing symfony/yaml (v3.4.4): Downloading (100%)
  - Installing tantek/cassis (v0.2.16895): Downloading (100%)
guzzlehttp/guzzle suggests installing psr/log (Required for using the Log middleware)
mf2/mf2 suggests installing barnabywalters/mf-cleaner (To more easily handle the canonical data php-mf2 gives you)
facebook/graph-sdk suggests installing paragonie/random_compat (Provides a better CSPRNG option in PHP 5)
symfony/yaml suggests installing symfony/console (For validating YAML files using the lint command)
Generating autoload files
```

I ran the update, as suggested:
```
# php composer.phar update
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 7 updates, 1 removal
  - Removing miniflux/picofeed (v0.1.37)
  - Updating facebook/graph-sdk (5.6.1 => 5.6.2): Downloading (100%)
  - Installing p3k/picofeed (v0.1.38): Downloading (100%)
  - Updating mf2/mf2 (v0.3.2 => v0.4.3): Downloading (100%)
  - Updating p3k/http (0.1.5 => 0.1.7): Downloading (100%)
  - Updating ezyang/htmlpurifier (v4.9.3 => v4.10.0): Downloading (100%)          - Updating p3k/xray (v1.4.2 => v1.4.23): Downloading (100%)
  - Updating guzzlehttp/guzzle (6.3.0 => 6.3.2): Downloading (100%)
  - Updating symfony/yaml (v3.4.4 => v3.4.8): Downloading (100%)
Writing lock file
Generating autoload files
```

Here are the errors:
```
[10-Apr-2018 00:58:14] WARNING: [pool www] child 13 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined index: like_site in /var/www/html/known/micropub/nanopub.php on line 559"
[10-Apr-2018 00:58:14] WARNING: [pool www] child 13 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined index: repost_site in /var/www/html/known/micropub/nanopub.php on line 573"
[10-Apr-2018 00:58:14] WARNING: [pool www] child 13 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined index: replysite in /var/www/html/known/micropub/nanopub.php on line 587"
[10-Apr-2018 00:58:14] WARNING: [pool www] child 13 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\Yaml\ctype_digit() in /var/www/html/known/micropub/vendor/symfony/yaml/Inline.php:209"
[10-Apr-2018 00:58:14] WARNING: [pool www] child 13 said into stderr: "Stack trace:"
[10-Apr-2018 00:58:14] WARNING: [pool www] child 13 said into stderr: "#0 /var/www/html/known/micropub/vendor/symfony/yaml/Dumper.php(123): Symfony\Component\Yaml\Inline::dump('slug', 0)"
[10-Apr-2018 00:58:14] WARNING: [pool www] child 13 said into stderr: "#1 /var/www/html/known/micropub/vendor/symfony/yaml/Yaml.php(149): Symfony\Component\Yaml\Dumper->dump(Array, 2, 0, 0)"
[10-Apr-2018 00:58:14] WARNING: [pool www] child 13 said into stderr: "#2 /var/www/html/known/micropub/nanopub.php(243): Symfony\Component\Yaml\Yaml::dump(Array)"
[10-Apr-2018 00:58:14] WARNING: [pool www] child 13 said into stderr: "#3 /var/www/html/known/micropub/nanopub.php(754): write_file(Array, 'test test test', '../content/micr...')"
[10-Apr-2018 00:58:14] WARNING: [pool www] child 13 said into stderr: "#4 {main}"
[10-Apr-2018 00:58:14] WARNING: [pool www] child 13 said into stderr: "  thrown in /var/www/html/known/micropub/vendor/symfony/yaml/Inline.php on line 209"
172.17.0.1 -  10/Apr/2018:00:58:13 +0000 "POST /micropub/nanopub.php" 500
```

**Comment by dg01d** [comment]
Okay, there's a bit to unpack here. First of all, I've dealt with the undefined indices in #11 separately.

`composer.lock` is used by me to make sure that all installations of nanopub are reproducible, that every installation is using the same dependencies. I don't have a lot of dependencies, but I'm not following along each of them to keep at the bleeding edge. The versions set in `composer.lock` are there because they work. 

Can I ask that you'd try the installation again, but this time, don't run `$ composer update`?

If the error is still occurring, then if you could tell me how you're attempting to post, or what client you're using, that would be helpful in parsing what's going on.

**Comment by skpy** [comment]
I've removed `vendor` and performed a fresh `php composer.phar install` to get the correct versions.

```
[10-Apr-2018 13:02:49] WARNING: [pool www] child 1127 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\Yaml\ctype_digit() in /var/www/html/known/micropub/vendor/symfony/yaml/Inline.php:209"
[10-Apr-2018 13:02:49] WARNING: [pool www] child 1127 said into stderr: "Stack trace:"
[10-Apr-2018 13:02:49] WARNING: [pool www] child 1127 said into stderr: "#0 /var/www/html/known/micropub/vendor/symfony/yaml/Dumper.php(123): Symfony\Component\Yaml\Inline::dump('slug', 0)"
[10-Apr-2018 13:02:49] WARNING: [pool www] child 1127 said into stderr: "#1 /var/www/html/known/micropub/vendor/symfony/yaml/Yaml.php(149): Symfony\Component\Yaml\Dumper->dump(Array, 2, 0, 0)"
[10-Apr-2018 13:02:49] WARNING: [pool www] child 1127 said into stderr: "#2 /var/www/html/known/micropub/nanopub.php(243): Symfony\Component\Yaml\Yaml::dump(Array)"
[10-Apr-2018 13:02:49] WARNING: [pool www] child 1127 said into stderr: "#3 /var/www/html/known/micropub/nanopub.php(754): write_file(Array, 'test test test', '../content/micr...')"
[10-Apr-2018 13:02:49] WARNING: [pool www] child 1127 said into stderr: "#4 {main}"
[10-Apr-2018 13:02:49] WARNING: [pool www] child 1127 said into stderr: "  thrown in /var/www/html/known/micropub/vendor/symfony/yaml/Inline.php on line 209"
172.17.0.1 -  10/Apr/2018:13:02:49 +0000 "POST /micropub/nanopub.php" 500
```

Additional research suggests that this stems from a missing PHP extension: ctype.  I've tried to install that directly into my container, but the errors persist.  It's possible that this extension requires a restart of `php-fpm` which would require that I rebuild my container.  I'll work on this and report back.

**Comment by skpy** [comment]
That was it.  Rebuilding my container to include `php7-ctype` got everything working. You can close this now!  Thanks!
